name: Upload Latest Artifacts to Release

on:
  release:
    types: [released, edited]

jobs:
  package:
    name: Release New Slippi Playback Dolphin
    runs-on: ubuntu-latest
    steps:
      - name: 'Get version'
        run: |
          echo "VERSION=$(echo ${{ github.ref }} | cut -d "v" -f 2)" >> $GITHUB_ENV
      - name: Download latest artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: pr-build.yml
          branch: slippi
          repo: project-slippi/Ishiiruka
      - name: Organize release files
        run: |
          rm -rf *netplay*
          find ./ -mindepth 2 -type f -exec mv -t ./ -i '{}' +
          find . -type d -empty -delete
          mv *linux* "playback-${{ env.VERSION }}-Linux.zip"
          mv *.dmg "playback-${{ env.VERSION }}-Mac.dmg"
          mv *windows* "playback-${{ env.VERSION }}-Win.zip"
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
